# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eigenMapMatMult <- function(A, B) {
    .Call('_mnem_eigenMapMatMult', PACKAGE = 'mnem', A, B)
}

transClose_W <- function(x) {
    .Call('_mnem_transClose_W', PACKAGE = 'mnem', x)
}

transClose_Del <- function(x, u, v) {
    .Call('_mnem_transClose_Del', PACKAGE = 'mnem', x, u, v)
}

transClose_Ins <- function(x, u, v) {
    .Call('_mnem_transClose_Ins', PACKAGE = 'mnem', x, u, v)
}

maxCol_row <- function(x) {
    .Call('_mnem_maxCol_row', PACKAGE = 'mnem', x)
}

